### PR TITLE
Adds travis.yml

### PR DESCRIPTION
**Pull request by pedrocunha**

### CODE REVIEW

**Comment by pedrocunha** [comment]
@mezis do you mind setting up travis to this repo? I don't have permissions to do that.

**Comment by mezis** [comment]
@pedrocunha I'll try :)

**Comment by mezis** [comment]
Build started!

**Comment by pedrocunha** [comment]
@mezis cheers for that, looks like the build fails due to gettext problems. I guess probably the binaries are not present on travis. Will see if I can fix it.

**Pull request closed without merging**
